### ISSUE TITLE
cv2.estimateRigidTransform deprecated

### ISSUE THREAD

**Issue by DajaDaja** [georgegach/face-average#2]
Dear George,

many thanks for sharing your face averaging project here!
When trying to run 

`python ./run.py  -i "datasets/us-mp/president" -w -wt 200`

I encountered the following error:

```
Namespace(ext=None, height=400, input='datasets/us-mp/president', noCaching=False, noWarps=False, output=None, template=None, width=300, window=True, windowTime=200)
Faces detected: 1 in ...-regan.jpg: 100%|████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 1262.08it/s]
Loading: ...ident/ronald-regan.jpg: 100%|██████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 13.68it/s]
Warping: ...ident/bill-clinton.jpg:   0%|                                                                                  | 0/7 [00:00<?, ?it/s]Traceback (most recent call last):
  File "./run.py", line 27, in <module>
    Averager(width=options.width, height=options.height).run(path=options.input, ext=ext, window=options.window, showWarps=not options.noWarps, windowTime=options.windowTime, useCaching=not options.noCaching, template=options.template).save(name=options.output)
  File "./src/faceAverage.py", line 99, in run
    tform = self.similarityTransform(eyecornerSrc, eyecornerDst)
  File "./src/faceAverage.py", line 234, in similarityTransform
    tform = cv2.estimateRigidTransform(np.array([inPts]), np.array([outPts]), False)
AttributeError: module 'cv2' has no attribute 'estimateRigidTransform'
```

It seems like estimateRigidTransform was [deprecated](https://stackoverflow.com/questions/55757977/how-to-use-estimaterigidtransform-in-opencv-3-0-or-higher-is-there-any-other-al).

Are you planning to update the project? It would be fantastic to be able to use the tool.
Best wishes!

**Comment by emrecan-s** [comment]
Hi ,
Uninstall the opencv version you have and install the following one.
pip install opencv-python==3.4.2.16
Than it would work

**Comment by ankitvirla** [comment]
Thanku @emrecan-s  for this solution.
